# Generated by Django 3.2.4 on 2021-08-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
