# Generated by Django 3.2.4 on 2021-08-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chart_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='Cart',
        ),
    ]
