# Generated by Django 3.2.4 on 2021-08-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_image_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_string',
        ),
    ]
