# Generated by Django 3.2.4 on 2021-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_image_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
