# Generated by Django 3.2.4 on 2021-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_personaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='buyer_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
