# Generated by Django 3.2.4 on 2021-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cart_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('buyer', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
