# Generated by Django 3.2.4 on 2021-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_buynow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='', max_length=5)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
