# Generated by Django 3.2.4 on 2021-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_favouriteproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteproducts',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
