# Generated by Django 3.2.4 on 2021-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_favouriteproducts_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=5000)),
            ],
        ),
    ]
