# Generated by Django 3.2.4 on 2021-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
