# Generated by Django 3.2.4 on 2021-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_review_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='favouriteproducts',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='images/'),
        ),
    ]
