# Generated by Django 3.2.4 on 2021-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_favouriteproducts_added_to_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproducts',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
