# Generated by Django 3.2.4 on 2021-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_favouriteproducts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='apartment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='block',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='phone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldata',
            name='scara',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
