# Generated by Django 3.2.4 on 2021-09-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210906_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
