# Generated by Django 3.2.4 on 2021-09-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_favouriteproducts_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteproducts',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
