# Generated by Django 3.2.4 on 2021-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='postal_codee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
