# Generated by Django 3.2.4 on 2021-09-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_personaldata_postal_codee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='postal_codee',
            new_name='postal_code',
        ),
    ]
