# Generated by Django 3.1.7 on 2021-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210927_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='product_images/'),
        ),
    ]
