# Generated by Django 3.1.7 on 2021-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210930_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
