# Generated by Django 3.1.7 on 2021-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210930_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
