# Generated by Django 3.1.7 on 2021-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211007_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regislat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
