# Generated by Django 3.1.7 on 2021-10-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_product_regislat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='number',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='street',
        ),
    ]
