# Generated by Django 4.0.4 on 2022-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
