# Generated by Django 4.0.4 on 2022-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_delete_productimage_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
