# Generated by Django 4.0.4 on 2022-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproducts',
            name='image',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
