# Generated by Django 4.0.4 on 2022-08-09 19:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_orders_delete_personaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='products_id',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='products_name',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
