# Generated by Django 4.0.4 on 2022-07-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
